config/routes.rb
Rails.application.routes.draw do
  resources :airports
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "flights#index"
  resources :flights
  resources :passengers
  resources :bookings
end

app/models/airport.rb
class Airport < ApplicationRecord
  validates :code, presence: true,uniqueness: true
  validates :name, presence: true
  validates :address, presence: true
    has_many :departing_flights, class_name: 'Flight', foreign_key:"departure_airport_id"
    has_many :arriving_flights, class_name: 'Flight', foreign_key:"arrival_airport_id"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
    has_one :flight, foreign_key:"id"
    has_many :passenger
end

app/models/flight.rb
class Flight < ApplicationRecord
    belongs_to :departure_airport, class_name: 'Airport',primary_key:"id"
    belongs_to :arrival_airport , class_name: 'Airport',primary_key:"id"
    has_many :bookings, primary_key:"id"
end

app/models/passenger.rb
class Passenger < ApplicationRecord
    validates :name, presence: true
    has_many :bookings, foreign_key:"id"
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  before_action :set_airport, only: %i[ show edit update destroy ]

  # GET /airports or /airports.json
  def index
    @airports = Airport.all
  end

  # GET /airports/1 or /airports/1.json
  def show
  end

  # GET /airports/new
  def new
    @airport = Airport.new
  end

  # GET /airports/1/edit
  def edit
  end

  # POST /airports or /airports.json
  def create
    @airport = Airport.new(airport_params)

    respond_to do |format|
      if @airport.save
        format.html { redirect_to root_path, notice: "Airport was successfully created." }
        format.json { render :show, status: :created, location: @airport }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airports/1 or /airports/1.json
  def update
    respond_to do |format|
      if @airport.update(airport_params)
        format.html { redirect_to airport_url(@airport), notice: "Airport was successfully updated." }
        format.json { render :show, status: :ok, location: @airport }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airports/1 or /airports/1.json
  def destroy
    @airport.destroy!

    respond_to do |format|
      format.html { redirect_to airports_url, notice: "Airport was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_airport
      @airport = Airport.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def airport_params
      params.fetch(:airport).permit(:code,:name,:address)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    def new
        @Flight = Flight.find(params[:flight])
        @count = params[:count]
        Booking.find_or_create_by({flight_id:@Flight.id,count: @count})
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
    before_action :find_flights
    def index
        @flights = Flight.all
        if(!params[:departure].nil?)
            @departure_airports = Airport.where(id: params[:departure])
            @departureIsSet = true
        end
        if(!params[:departure].nil? && (params[:arrival] == "" || params[:arrival].nil?) )
            @arrival_airports=Flight.where(departure_airport_id: params[:departure]).collect{|f|f.arrival_airport}.uniq
        end
        if(!(params[:arrival] == "" || params[:arrival].nil?))
            @arrival_airports = Airport.where(id: params[:arrival])
            @arrivalIsSet = true
        end
        @dates=Flight.where(departure_airport_id: params[:departure]).where(arrival_airport_id: params[:arrival]).pluck(:departure_time).uniq || []
        @searchedFlights = Flight.where(departure_airport_id: params[:departure]).where(arrival_airport_id: params[:arrival])
        @count = params[:passenger]
    end

    def new
        @flight =Flight.new
    end
    
    def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to flight_url(@flight), notice: "Flight was successfully created." }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

    private
    def find_flights
        @departure_airports = Flight.all.collect{|f| f.departure_airport}.uniq
        @departureIsSet = false
        @arrival_airports=Flight.where(departure_airport_id: params[:departure]).collect{|f|f.arrival_airport}.uniq
        @arrivalIsSet = false
    end
    def flight_params
      params.fetch(:flight).permit(:model,:capacity,:arrival_airport_id,:departure_airport_id,:departure_time,:arrival_time)
    end
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
    def new
        
        @passengers = CGI.parse(URI.parse(request.fullpath).query)
        @passengers["name"].length.times do |i|
            Passenger.find_or_create_by({name:@passengers["name"][i], email:@passengers["email"][i]})
            PassengerMailer.welcome_email(Passenger.new(name:@passengers["name"][i], email:@passengers["email"][i])).deliver_now
        end

    end
    def index
    end
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/airports/_airport.html.erb
<div id="<%= dom_id airport %>">
<h1>Airport <%=airport.code%></h1>

</div>

app/views/airports/_form.html.erb
<%= form_with(model: airport, class:"space-y-5 space-x-5") do |form| %>
  <% if airport.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(airport.errors.count, "error") %> prohibited this airport from being saved:</h2>

      <ul>
        <% airport.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%=form.label :code, "Airport Code"%>
  <%=form.text_field :code, class:"rounded",placeholder:"AIR"%>
  <%=form.label :name, "Airport Name"%>
  <%=form.text_field :name,class:"rounded",placeholder:"Air International Airport"%>
  <%=form.label :address, "Airport Address"%>
  <%=form.text_field :address, class:"rounded",placeholder:"Earth"%>

  <div>
    <%= form.submit class: "rounded my-2 p-2 bg-green-500 hover:bg-green-700" %>
  </div>
<% end %>

app/views/airports/edit.html.erb
<h1>Editing airport</h1>

<%= render "form", airport: @airport %>

<br>

<div>
  <%= link_to "Show this airport", @airport %> |
  <%= link_to "Back to airports", airports_path %>
</div>

app/views/airports/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Airports</h1>

<div id="airports">
  <% @airports.each do |airport| %>
    <%= render airport %>
    <p>
      <%= link_to "Show this airport", airport %>
    </p>
  <% end %>
</div>

<%= link_to "New airport", new_airport_path %>

app/views/airports/new.html.erb
<div class="backdrop-blur-sm border-2 rounded  border-white self-center py-5 content-center px-10 w-11/12 mt-5 h-fit">
<%= link_to "Odin Flight Booking", root_path, class:"rounded-lg w-full text-6xl font-sans text-blue-950 font-bold italic mx-10 hover:backdrop-blur-xl transition-all"%>
</div>

<div class="backdrop-blur-sm border-2 rounded border-white self-center py-5 content-center px-10 w-11/12 mt-5 h-fit">
<h1 class="text-2xl font-semibold pb-5 ">New airport</h1>

<%= render "form", airport: @airport %>

<br>

<div>
    <%= link_to "Back to root", root_path, class:" bg-blue-500 p-2 rounded hover:bg-blue-700" %>
</div>
</div>

app/views/airports/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @airport %>

<div>
  <%= link_to "Edit this airport", edit_airport_path(@airport) %> |
  <%= link_to "Back to airports", airports_path %>

  <%= button_to "Destroy this airport", @airport, method: :delete %>
</div>

app/views/bookings/new.html.erb
<div class="backdrop-blur-sm border-2 rounded  border-white self-center py-5 content-center px-10 w-11/12 mt-5 h-fit">
<%= link_to "Odin Flight Booking", root_path, class:"rounded-lg w-full text-6xl font-sans text-blue-950 font-bold italic mx-10 hover:backdrop-blur-xl transition-all"%>
</div>
<div class=" my-6 border-white border-2 space-y-3 px-5 py-4 self-center w-11/12 backdrop-blur-md">
<h1 class="text-4xl py-4 font-bold font-mono"> New Booking</h1>
<h1 class="text-2xl font-semibold">Details of the Flights</h1>
<div class="">
<div class="flex gap-5">
<h2> Id: <%=@Flight.id%></h2>
<h2 class="ml-8"> Departure: <%=@Flight.departure_airport.code%></h2>
<div class="text-xl ml-10"> 🛫  ---></div>
<h2> Arrival: <%=@Flight.arrival_airport.code%></h2>
</div>
<div class="flex gap-5">
<h2> Count: <%=@count%></h2>
<h2> Departure Time: <%=@Flight.departure_time%></h2>
<h2 class="ml-10"> Arrival Time: <%=@Flight.arrival_time%></h2>
</div>
</div>
</div>

<%= form_with url: new_passenger_path,class:"backdrop-blur-md border-white border-2 space-y-2 px-5 py-4 w-11/12 self-center", method: :get do |f|%>
<h1 class="text-2xl font-semibold pb-5">Enter the details of Passenger(s)</h1>
<%= hidden_field_tag "count", @count%>
<%= hidden_field_tag "flight", @Flight.id%>
    <%@count.to_i.times do |i| %>
     <div class="flex gap-5 align-middle">
        <div class="pl-5 w-fit"><%="Passenger "+(i+1).to_s%></div>
        <%= f.text_field :name, input_html:{multiple:true},:class =>"rounded", :placeholder => "Name" %>
        <%= f.text_field :email,input_html:{multiple:true},:class =>"rounded", :placeholder => "Email" %>
        <br><br>
    </div>
    <%end%>
    <%=f.submit "Submit",class:"bg-green-500 rounded hover:bg-green-700 p-2"%>
<%end%>

app/views/flights/index.html.erb
<div class="backdrop-blur-sm border-2 rounded  border-white self-center py-5 content-center px-10 w-11/12 mt-5 h-fit">
<%= link_to "Odin Flight Booking", root_path, class:"rounded-lg w-full text-6xl font-sans text-blue-950 font-bold italic mx-10 hover:backdrop-blur-xl transition-all"%>
</div>
<div class="px-10 space-y-5 w-11/12 backdrop-blur-sm font-semibold bg-white/5 border-2 border-white rounded-md self-center p-5">
    <h2 class="py-5 bold text-4xl font-Sans ">Search Flights</h2>
    <%= link_to "Reset Form", root_path, class:"rounded-md text-white bg-red-500 opacity-75 p-2 hover:bg-red hover:opacity-100  transition"%>

    <%= form_with url:"/flights",name:"search_plane", class:"", method: :get do |form| %>
        <%= form.label :departure, "Departure Airport" %>
        <%= form.collection_select :departure, @departure_airports, :id, :code,{:prompt => ! @departureIsSet}, {:class=>"rounded mx-5",:onchange => "this.form.submit();"} %>

        <%= form.label :arrival, "Arrival Airport" %>
        <%= form.collection_select :arrival, @arrival_airports, :id, :code,{:prompt => ! @arrivalIsSet},{:class=>"rounded mx-5",:onchange => "this.form.submit();"} %>

        <%= form.label :passenger, "Number of Passengers" %>
        <%= form.select :passenger, options_for_select((1..4).to_a),{}, {:class=>"rounded mx-5",:onchange =>"this.form.submit()"} %>

        <%= form.label :date, "Date of travel" %>
        <%= form.select :date, @dates, {}, {:class=>"mx-5 rounded",onchange:"this.form.requestSubmit()"}  %>
<br>
        <%= form.submit "Search 🔎", class:"bg-blue-600 text-white p-2 my-2 rounded hover:bg-blue-800"%>
    <% end %>
    

    <h1 class="font-semibold text-3xl">Searched Flights</h1>
    <%= form_with url: new_booking_path, method: :get do |f| %>
        <%= hidden_field_tag :count, @count%>
        <% @searchedFlights.each do |flight| %>
            <%= f.radio_button :flight, flight.id%>
            <%= f.label :flight, "Flight #{flight.id} - #{flight.departure_airport.code} to #{flight.arrival_airport.code} on #{flight.departure_time} - #{flight.arrival_time}", class:"mx-2" %>
            <br><br>
        <%end%>
        <%if @searchedFlights.length > 0%>
            <%= f.submit "Book Flight", class:"bg-green-500 text-white px-2 py-2 rounded hover:bg-green-700"%>
        <%end%>
    <%end%>

</div>

<div class="backdrop-blur-sm border-2 rounded  border-white self-center py-5 content-center px-10 w-11/12 mt-5 h-fit">
<h1 class="text-4xl font-semibold pb-5">Admin Panel</h1>
 <%= link_to 'Create new Airport', new_airport_path, class:"p-2 mr-5 rounded bg-lime-400 hover:bg-lime-700" %>
 <%= link_to 'Create new Flight', new_flight_path,class:"p-2 rounded bg-lime-400 hover:bg-lime-700" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>✈️ Odin Flight Booker ✈️</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="bg-cover bg-[url('https://images.pexels.com/photos/957768/pexels-photo-957768.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1')] from-cyan-500 to-blue-500- w-screen h-screen ">
      <div class="flex flex-col space-y-8 ">
      <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/passengers/new.html.erb
<div class="backdrop-blur-sm border-2 rounded  border-white self-center py-5 content-center px-10 w-11/12 mt-5 h-fit">
<%= link_to "Odin Flight Booking", root_path, class:"rounded-lg w-full text-6xl font-sans text-blue-950 font-bold italic mx-10 hover:backdrop-blur-xl transition-all"%>
</div>
<div class="backdrop-blur-sm border-2 rounded  border-white self-center py-5 content-center px-10 w-11/12 mt-5 h-fit">
<h1 class="text-6xl py-5">Booking Created Successfully</h1>
<%= link_to 'Return Home', root_path,class:"bg-green-500 p-2 hover:bg-green-700 rounded" %>
</div>